### ISSUE TITLE
status details in HomeKit showing "is heating" despite it isn't

### ISSUE THREAD

**Issue by marck1991** [normen/homebridge-platform-maxcube#11]
In HomeKit app at the top the status details are shown.
In there in my case are the wall thermostat temperatures shown with the text addition "is heating" despite it isn't because room temperature is 22° and set value is 17° (for me the exact shown german text value is "Wird geheizt.".
So the full line is for example: "Wohnzimmer 22°. Wird geheizt."

If the system is really heating the shown text is "heating..." (for me the exact shown german text value is "heizen...".
So the full line is for example: "Wohnzimmer 22°. heizen..."

Is there a way to change that if the system isn't heating that there is no additional text to the shown temperatures?
I know this is cosmetic :)

**Comment by normen** [comment]
Yes it is in heating mode, just not currently opening the valve because the temperature is set to 17 degrees. If you want to read "off" then turn the thermostat off.

This is nothing the plugin has control over really, HomeKit (or you) would have to be smart enough to realize that when a thermostat is set to "heating" and the temperature is above the heating temperature that it technically is not actually heating at that moment.

However - if I was to look at HomeKit I would want to know what the thermostat is set to do, not what it's currently doing because - as said - the latter is pretty easy to conclude for yourself.
