### ISSUE TITLE
homebridge don't start because of Max

### ISSUE THREAD

**Issue by stalkerj** [normen/homebridge-platform-maxcube#19]
Hello.
I added config with Max and home bridge don't want to start.
Here is I got in log:

[9/28/2019, 9:42:16 PM] [MaxCube Platform] Max! Cube could not be found, please restart HomeBridge with Max! Cube connected.
[9/28/2019, 9:42:16 PM] [MaxCube Platform] Max! Cube connection closed.

**Comment by normen** [comment]
As the log says, the MaxCube can't be found by the plugin. Thats because all your configured thermostat devices in HomeKit would be lost if the HomeBridge server boots without knowing about all thermostat devices - so the plugin blocks the HomeBridge boot process to keep that fro happening. Make sure your MaxCube has a fixed IP and its correctly set in the config.json settings.

**Comment by stalkerj** [comment]
I’m sure about fixed ip. It worked for few years before. Now it’s not working anymore. I scanned my network, i saw that max has ip 10.0.1.16 and the same in my config. Can it be other problem?

**Comment by stalkerj** [comment]
I just reseted my Max cube, added all the thermostat again. It works in max web interface but homebridge has the same error in logs. I entered the same ip in max web interface as I have in my config.

**Comment by normen** [comment]
Did you scan the network _from_ the Pi where HomeBridge runs on? Anyway, I can't help much here, the cube apparently can't be found by the plugin.. If theres no other stack traces or error messages then thats what the network stack of Node.js reports, hinting at a deeper issue.

**Comment by Majusus118** [comment]
Hey normen,
i got the same issue. IP is fixed and config.json is also correct but homebridge is not able to find the Cube.

**Comment by normen** [comment]
Make sure you _do not_ enable internet control in the cube - as the README states.
