### ISSUE TITLE
wall thermostats are shown, although this is not activated

### ISSUE THREAD

**Issue by D4WauS** [normen/homebridge-platform-maxcube#33]
Hello,
I am using Homebridge to integrate the Max! heating control into Apple HomeKit. This works quite well so far. Recently, however, the wall thermostats are also displayed, although this is not activated both in the configuration and in the settings of the plugin. The effect is that both the radiator thermostat and the wall thermostat are displayed for each room and, if necessary, two measured temperatures are displayed in the status. This is disturbing.

Stephan

**Comment by normen** [comment]
"Recently however"? So you say that you always had thermostats, they didn't appear previously and now they do? I really can't imagine how that would happen. Did you update any of the components?

**Comment by D4WauS** [comment]
I had set "allow_wall_thermostat" to "true" once to try this out. But after changing it back to "false" they remain visible.

**Comment by normen** [comment]
That makes more sense. Since 2.0 theres automatic detection of devices, once they passed through the initial check they're in the device cache. I guess at some point there could be additional checks on each boot for such situations.

To work around this you could:
- Remove the whole plugin config section in homebridge and reboot once, then set it up again
- Remove the wall thermostat in the Max! software and reboot homebridge once (then add it again in Max!)
- Find & remove the entry for that thermostat in your cached-accessories file

**Comment by D4WauS** [comment]
Thx
