### ISSUE TITLE
two or more cubes in one network

### ISSUE THREAD

**Issue by mueckehh** [normen/homebridge-platform-maxcube#41]
Hi, I have two Max! cubes in my network to separate two families in the same house and to get a more robust installation. Now I tried to setup your plugin for the two in one HomeBridge installation. If I add in the config file the second cube I receive an error that the Max! Link object could not be generated because there is already one in place.

At the moment I installed a second Raspi, but this is not my general idea. Is there any possibility to integrate the two (or more) cubes in one HomeBridge instance?

Thank you for your support

Remark: the plugin works fantastic, thank you for creating this...

**Comment by normen** [comment]
The plugin supports this as far as homebridge does. Afaik the HB team decided to remove support for multiple platforms in one homebridge instance. Maybe check if thats really an "error" or just one of the annoying warnings they added in 1.3, maybe it actually still works.

Otherwise instead of setting up more hardware (RasPi), just run a second homebridge instance on the existing one, thats what I do, also to avoid congestion and HomeKits 100 device limit for one bridge.
