### ISSUE TITLE
Allow enabling ECO mode from HomeKit

### ISSUE THREAD

**Issue by mark82436** [normen/homebridge-platform-maxcube#6]
I have on my MaxCube config the ECO Wall Switch
for Eco or Auto switching.

are nice to have this funktion at homekit
to switching form Auto to Eco and Eco to Auto Mode for all thermostate

https://www.amazon.de/Max-99011-MAX-Taster-99011A0/dp/B004W1PTNG/ref=sr_1_1?s=diy&ie=UTF8&qid=1520429917&sr=1-1&keywords=MAX%21+Eco+Taster

**Comment by normen** [comment]
I don't know why you would want the switch inside of HomeKit? The Eco switch will do what it's supposed to do and the thermostats in HomeKit will show the temperature accordingly.

**Comment by thorstendorn** [comment]
I would rather use HomeKit to implement what the botton does in a more clever way: E.g. „set all temperatures to ECO when the last person (=iPhone) left the house.“

**Comment by normen** [comment]
Yeah exactly, you can easily do that when you have cooling = eco in HomeKit. You make a scene where all devices are set to "cooling" which you can then call whenever you like. You can also just have parts of your house in one scene to make an "eco button" in HomeKit for say the guest flat.

**Comment by mark82436** [comment]
I would have to do all the thermostats in Homekit, although I already have everything in the MaxCube. It would be of advantage to have a software switch.
Then the whole Intelegenz in the MaxCube and not in HomeKit would be.
The control in the MaxCube also works more reliably than the Homekit version

**Comment by normen** [comment]
Just so I know exactly how the button works, when you press the eco button the devices are all set to their "eco" temperature - obviously. Then when there is a change in the Max! plan do they set the temperature to the planned one or do they stay in "eco" mode?

**Comment by thorstendorn** [comment]
They stay in ECO. The idea is to place the button next to your house’s exit. When you leave just press it and save energy. Would not make sense, if the thermostats changed to their schedule afterwards. ;-)

**Comment by mark82436** [comment]
sorry my english is not so good 

When I press the eco button, the whole system goes into eco mode and sets the temperature to the values programmed in the eco mode. when the head is pressed again, everything goes back to auto mode and the normal weekly programs continue.

**Comment by mark82436** [comment]
if the button in the home kit would be then you could switch from the road again in the auto mode and does not have to wait until you're home and the button presses. The function can also be found in the max app

**Comment by mark82436** [comment]
![max_app_ipone_5s_schwarz_de_1](https://user-images.githubusercontent.com/35312129/37103146-d6d869c0-2229-11e8-9004-ea4f38921d8d.png)

**Comment by normen** [comment]
Okay so it only makes sense to display ONE eco button in HomeKit then right? Not one per actual hardware button? Because they always control everything, correct?

I have to look if its possible to extend the maxcube2 library to send the actual global "eco" command to the cube. If thats not possible I'll look into emulating that behavior at least.

Thanks for the information @all - this is very helpful.

**Comment by thorstendorn** [comment]
Oh yes, you are right that is true! With some geofencing added through another Homebridge plug in, there would be a feature like tado offer. ...and you got rid of the need to press a „button“ while you are on the road.

**Comment by mark82436** [comment]
yes exactly it would be enough for a button (eco) on / off

**Comment by normen** [comment]
Okay. Well if you want that feature (geofencing -> off/on) NOW you can do it like me. I basically enable it by making a scene where all thermostats are set to manual mode and some temperature (17deg in my case) and another one where I set to auto mode and my preferred temperatures. Then those are called when I arrive/leave.

Granted, I had to make a scene with all thermostats for both settings but if you actually have an ECO button then switching the temperature with the button before making that scene in HomeKit will automatically insert all the correct temperatures. So you only need to make a scene, select the radiators and are done - well except for setting manual mode for all thermostats in one of the scenes.

So thats a workaround for now if you like :) I'll update this issue when the homebridge-platform-maxcube@beta includes any news in this direction.

**Comment by mark82436** [comment]
yes it is a nice to have

**Comment by normen** [comment]
Okay I checked and according to the manual the eco button does EXACTLY the same as what I just described. So I will have to "emulate" it by setting all thermostats to manual mode and their specific eco temperature. There is no global command, the maxcube does the same when it receives an ECO button signal.

**Comment by normen** [comment]
And thinking further this is really a bit of a dumb situation.. That scene you'd create would also very nicely show if eco mode is still enabled or not. It would basically be a perfect eco button in HomeKit.

Because HomeKit keeps track of the state of the buttons you could press the eco button and the scene would light up. Then you'd change a single thermostat any way you want and it'd turn off. Same for a "comfort temperature" scene. You could easily select and call them..

If I made switches for eco/comfort they would have to do the same thing, track the state of all thermostats and update their state based on that, thats a lot of ugly code if HomeKit already does that..

**Comment by mark82436** [comment]
ok then we leave it if there is not a global command

**Comment by normen** [comment]
Well I'm open for further thoughts on this. For now I'll implement actual handling of the eco/comfort temperatures in Max! in the plugin as described, then we can see how to go on further.

**Comment by normen** [comment]
That was easier than I thought, setting the mode between off/heating/cooling/auto now changes the temperatures according to the temperatures set in the Max! cube.

You can try the beta using this command:
`npm install -g homebridge-platform-maxcube@beta`

**Comment by mark82436** [comment]
i have install
and set it to cooling 

`[2018-3-7 18:54:31] [MaxCube] Wandthermostat 1 (Esszimmer) - setting mode MANUAL at temperature 16.5
Uncaught exception error:  ReferenceError: that is not defined
    at Thermostat.checkHeatingCoolingState (/usr/local/lib/node_modules/homebridge-platform-maxcube/thermostat.js:153:7)
    at Thermostat.refreshDevice (/usr/local/lib/node_modules/homebridge-platform-maxcube/thermostat.js:118:10)
    at emitOne (events.js:121:20)
    at MaxCube.emit (events.js:211:7)
    at MaxCubeLowLevel.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube.js:76:14)
    at emitOne (events.js:116:13)
    at MaxCubeLowLevel.emit (events.js:211:7)
    at /usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:43:14
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:39:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
Uncaught exception error:  ReferenceError: that is not defined
    at Thermostat.checkHeatingCoolingState (/usr/local/lib/node_modules/homebridge-platform-maxcube/thermostat.js:153:7)
    at Thermostat.refreshDevice (/usr/local/lib/node_modules/homebridge-platform-maxcube/thermostat.js:118:10)
    at emitOne (events.js:121:20)
    at MaxCube.emit (events.js:211:7)
    at MaxCubeLowLevel.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube.js:76:14)
    at emitOne (events.js:116:13)
    at MaxCubeLowLevel.emit (events.js:211:7)
    at /usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:43:14
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-platform-maxcube/node_modules/maxcube2/maxcube-lowlevel.js:39:16)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)`

**Comment by normen** [comment]
Thank you very much, having somebody actually try the beta is so helpful.

I updated the beta, can you try again by installing again using the same command?

**Comment by mark82436** [comment]
yes i can do

**Comment by normen** [comment]
I changed a few more things. Note the buttons don't do the same as on the Max! device, when you set the heating or auto modes they will only change the temperature if it was off before, otherwise they just enable manual/auto. This is to avoid issues when scenes in HomeKit first send a temperature change and then a mode change because both are saved in a scene.

Otherwise everything seems to work fine for me. HomeKit shows the mode you set on the thermostat as off/cooling/heating/auto and you can enable the eco mode with the "cooling" setting. You can switch between manual and auto with the "heating/auto" settings and turn the thermostat off with the "off" setting.

**Comment by mark82436** [comment]
hello norman
i am not @home 
i can test it at the next week

**Comment by thorstendorn** [comment]
I have installed the beta(a) yesterday. Have not specifically tested anything, but cannot identify any issue, either. Thumbs up!

**Comment by thorstendorn** [comment]
...beta(s)...

**Comment by normen** [comment]
Cool, thanks. I‘m doing the same, testing it further. Please report any issues, if you could keep on using the beta until 1.1.0 is finally released that‘d be awesome, that way theres more overall testing time :)

**Comment by normen** [comment]
Guys, thanks so much for testing!

I released 1.1.0 now, I guess that version will be out longer than 6 days ;) Except of course for 1.1.x bug fixes in case there are any left.

Otherwise I guess the next possible feature additions can only come when HomeKit gets new features for thermostat devices. If anyone comes up with a nice feature to add start an issue here and we can evaluate it.
