### ISSUE TITLE
Interval for measured temperature

### ISSUE THREAD

**Issue by nco1512** [normen/homebridge-platform-maxcube#9]
hi normen,
is it possible to set an interval for the measured temperature of the thermostat's? 
Like get the temperature every 30mins, or is there any other way to get the actual temperature without setting the temperature of the thermostat?

**Comment by normen** [comment]
So, you're apparently observing a behavior where the thermostat only reports the measured temperature when you're sending a value to the thermostat? The cube is polled for the temperatures every 10 seconds so that can't be it.

Are you sure that's what's happening? The Max! Cube tries to keep the radio communication to the thermostats to a minimum and so a forced communication (setting the temperature) will also update the measured temperature. But from what I see in my system I eventually also get temperature changes without setting the temperature. Maybe you're just impatient?

Otherwise you might want to look at this to find out if theres any additional request to send but remember the cube has to limit the communication to some extent.
https://github.com/Bouni/max-cube-protocol
